### ISSUE TITLE
No license = not possible to legally use

### ISSUE THREAD

**Issue by skylarmt** [atarw/material-ui-swing#1]
This project has no code license attached.  This means that (in many countries) it defaults to "all rights reserved" implied copyright.  This means it's technically copyright infringement to use this code.

I would suggest [the MIT license](https://opensource.org/licenses/MIT), as it allows for anyone to use your code for anything they want, as long as they give you credit for it and include a copy of the MIT license.

**Comment by atarw** [comment]
added the MIT license 🙂

**Comment by skylarmt** [comment]
That was insanely fast!
