### ISSUE TITLE
Caret Colour for dark themes

### ISSUE THREAD

**Issue by mikera** [atarw/material-ui-swing#100]
I noticed on the dark themes it is very difficult to see the caret in text fields because it looks like the default caret colour (black?) is always being used.

I have a quick and dirty fix in this branch, testing with the Oceanic theme which changes the caret colour to white:
https://github.com/nuroko/material-ui-swing/tree/caret-colour

Let me know if you would like a PR for this?

**Comment by vincenzopalazzo** [comment]
Hi @mikera,

Thanks for work, yes it is a good feature, but you remember to alienate the propriety with MaterialTheming System.

I have a question, you can use the same color foreground for set the caret color, this is an good solution?

P.S: I'm working to release the new code of the library, you want to work the newest code of library you can see wait for my next commit or you can work with [this branch](https://github.com/vincenzopalazzo/material-ui-swing/tree/development)

Now I don't want break your work, so I will release the new code of the library when you have finished work or you can send me other details.

Thanks.

**Comment by mikera** [comment]
Hi I made a quick PR - not sure if this is the best way to do it but it works for the scenarios I have tested.

**Comment by vincenzopalazzo** [comment]
Fixed
