### ISSUE TITLE
Problem with resizing JDialog

### ISSUE THREAD

**Issue by izemskov** [atarw/material-ui-swing#105]
I try to use your MaterialDesign LookAndFeel in my project and I have a problem with resizing JDialog modal window. You can see this bug if change JFrame to JDialog in your example form and move mouse to right down corner. You don't see change mouse cursor to cursor for resizing. Also if you move mouse cursor to down edge of form you may see change cursor for resizing but resize don't work correctly. Please fix this bug and thank you for your work. It's very important to develop swing direction in Java

**Comment by vincenzopalazzo** [comment]
Hi @izemskov.

Thanks for using this l&f.

I know this bug and I'm working now to optimizing it, but the solution already existed with [this PR](https://github.com/vincenzopalazzo/material-ui-swing/pull/118).

If you use your app for simple cases and want to try the solution, you can compile this [vincenzopalazzo/material-ui-swing/development](https://github.com/vincenzopalazzo/material-ui-swing/tree/development).
After the build, you should have a `material-ui-swing-1.1.1_0.X-dev`.

You can see the actual bug status inside this [issue](https://github.com/vincenzopalazzo/material-ui-swing/issues/128) 


I hope to help with your issue and also, I suggest you see inside this repository [vincenzopalazzo/material-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing/tree/master). it contains the actual status of this l&f.

**Comment by vincenzopalazzo** [comment]
Fixed in material-ui-swing-1.1.1-rc1, look here https://github.com/vincenzopalazzo/material-ui-swing/releases

**Comment by izemskov** [comment]
It's really works! Thank you!

**Comment by vincenzopalazzo** [comment]
Hi @izemskov,

Happy to help :)
