### ISSUE TITLE
JOptionPane messageType parameter

### ISSUE THREAD

**Issue by MC501422** [atarw/material-ui-swing#112]
JOptionPane no visualization in **messageType parameter**
example:
JOptionPane.showMessageDialog(this, "Opcion invalida", "Opcion invalida", **JOptionPane.ERROR_MESSAGE)**;

![JOptionPane](https://user-images.githubusercontent.com/64989628/125589909-1d89696d-0d12-4772-ad5e-1a956b481822.png)

**Comment by vincenzopalazzo** [comment]
Hi @MC501422,

Thanks for this ticket, What is the behavior that you want to see?

Can you give also an example of the correct behavior with the Native Swing l&f?

**Comment by vincenzopalazzo** [comment]
P.S: As mentioned in the readme the developing phase is moving in the following repo https://github.com/vincenzopalazzo/material-ui-swing maybe it is the correct place to open an issue or a discussion to talk about your problem.

Thanks
