### ISSUE TITLE
How to customize the LaF?

### ISSUE THREAD

**Issue by wiese42** [atarw/material-ui-swing#19]
It is unclear to me how to customize the LaF without modifying the source code. Example: I would like to have my button background gray. How would I do that?

Currently my approach is to change the MaterialButtonUI to something like

Color bg = (Color)UIManager.get("Button.background");
if(bg != null) button.setBackground(bg);

and change MaterialLookAndFeel.initComponentDefaults to include
table.put ("Button.background", LIGHT_BLUE_400);

In my application code I then use

UIManager.put("Button.background", MaterialColors.GRAY_100)
UIManager.setLookAndFeel(MaterialLookAndFeel())

**Comment by wiese888** [comment]
I just realized that you don't have to set anything within the MaterialUI components. Just put everything in the initComponentDefaults section instead ( except for the stuff where you think that this part of the style should never be customized by the user. Would be great if you could change that in the future,. By the way I really like your LaF. Keep up the good work!

**Comment by atarw** [comment]
I'll need to research this a bit more since doing it the straightforward way seems to have odd side effects

**Comment by atarw** [comment]
This is now supported by all components except PasswordField and TextField, I'll need to refactor those a bit more

**Comment by wiese42** [comment]
Could you make table.rowHeight customizable as well? Suggestion:

MaterialTableUI.installUI

//by default "Table.rowHeight" will not be set in MaterialLookAndFeel.initComponentDefaults
int rowHeight = UIManager.getInt("Table.rowHeight");
if(rowHeight > 0)
  table.setRowHeight(rowHeight);
else
  table.setRowHeight (table.getRowHeight () + 25);

This way I can do something like UIManager.put("Table.rowHeight", 32) to get my desired row height.

**Comment by wiese42** [comment]
Could you make the combobox arrow button customizable as well? Suggestion:

MaterialComboBoxUI.createArrowButton:

Icon icon = UIManager.getIcon("ComboBox.buttonIcon");
JButton button;
if(icon != null) button = new JButton(icon);
else button = new BasicArrowButton (SwingConstants.SOUTH);
...

This way one can customize the arrow, e.g.
 UIManager.put("ComboBox.buttonIcon", ImageIcon(MaterialImages.DOWN_ARROW))
which looks nicer, I think.

**Comment by wiese42** [comment]
Could you make the spinner prev/next buttons customizable as well, so one can do something like

UIManager.put("Spinner.previousButtonIcon", ImageIcon(MaterialImages.DOWN_ARROW))
UIManager.put("Spinner.nextButtonIcon", ImageIcon(MaterialImages.UP_ARROW))

**Comment by atarw** [comment]
I'm going to be busy until Monday, but if you add it in as a pull request I'll merge it with the main repository :)
