### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Yemeen** [atarw/material-ui-swing#2]
How would you recommend implementing this repo? I am running into issues and I suspect I didn't use it correctly

**Comment by atarw** [comment]
download the latest release from [here](https://github.com/atarw/material-ui-swing/releases) and add the .jar file to your project

for example if you use intellij, [these](https://www.jetbrains.com/help/idea/import-existing-sources-libraries.html) [links](https://stackoverflow.com/questions/1051640/correct-way-to-add-external-jars-lib-jar-to-an-intellij-idea-project) might be helpful
