### ISSUE TITLE
JTextArea doesn't react to command keys anymore

### ISSUE THREAD

**Issue by wiese42** [atarw/material-ui-swing#21]
WIth this LaF active, nothing happens in JTextArea, if you press the arrow keys, backspace, and all the other command keys.  Could't figure out the reason for that.

**Comment by wiese42** [comment]
Just found out the reason for it. You need to set

 UIManager.put("TextArea.focusInputMap", multilineInputMap)
 UIManager.put("TextPane.focusInputMap", multilineInputMap)
 UIManager.put("EditorPane.focusInputMap", multilineInputMap)

See MetalLookAndFeel.java for some inspiration on how to initialize the inputMap.

**Comment by atarw** [comment]
Thank you for the pull request :D
I'll assume this issue is closed
