### ISSUE TITLE
Please support RadioButtonMenuItem

### ISSUE THREAD

**Issue by wiese42** [atarw/material-ui-swing#30]
Tried this myself but failed. Unclear how to customize the checked/unchecked icon.

**Comment by atarw** [comment]
Merged the pull request, but I'll leave this issue open in case any of you feel more changes need to be made

**Comment by vincenzopalazzo** [comment]
@atarw Yes, my solution works, but surely there will be some better solution

**Comment by wiese42** [comment]
This works, but is not configurable without modifying the code. Could you please fetch values from properties
RadioButtonMenuItem.checkIcon
RadioButtonMenuItem.selectedCheckIcon
RadioButtonMenuItem.backgorund
...

thx!

**Comment by vincenzopalazzo** [comment]
@wiese42 I try to make the changes

**Comment by vincenzopalazzo** [comment]
@wiese42 Now he should do what he has to do

**Comment by atarw** [comment]
Merged

**Comment by wiese42** [comment]
Looking good now! Thanks!
