### ISSUE TITLE
JFileChooser support

### ISSUE THREAD

**Issue by user12043** [atarw/material-ui-swing#32]
JFileChooser window appears empty. Here is screenshots from my app.

![ss1](https://user-images.githubusercontent.com/27023329/44151691-f8d952d6-a0ab-11e8-9bcd-d08717179340.png)
![ss2](https://user-images.githubusercontent.com/27023329/44151694-fbb9c92c-a0ab-11e8-94f4-b96244ed63b6.png)

**Comment by atarw** [comment]
I can add support for it as soon as I get back from work

**Comment by user12043** [comment]
Thanks, looking forward to

I will try also.

**Comment by atarw** [comment]
Added support

**Comment by user12043** [comment]
Thanks for quick support :smile:
