### ISSUE TITLE
Can not delete text in JTextPane

### ISSUE THREAD

**Issue by user12043** [atarw/material-ui-swing#33]
Content in JTextPane can not deleting with "Backspace" or "Delete" keys. Here is screenshot from my app.

![ss3](https://user-images.githubusercontent.com/27023329/44152415-28be7c4a-a0ae-11e8-9eb4-f78ce3fead2f.png)

**Comment by vincenzopalazzo** [comment]
I think the problem is due to the lack of component support, I try to see if I can make an implementation and if I can do it I'll make a pull request

**Comment by vincenzopalazzo** [comment]
@user12043 I think your problem was solved, I opened a pull request

**Comment by atarw** [comment]
Thank you so much for your help today 😄, I really appreciate it!

**Comment by vincenzopalazzo** [comment]
You don't have to thank me! 😁

**Comment by user12043** [comment]
Thanks for quick support :smile:
