### ISSUE TITLE
JLabels are opaque

### ISSUE THREAD

**Issue by hasankaWi** [atarw/material-ui-swing#41]
Hi, maybe I missed something but is there a way to set the labels not opaque?

**Comment by vincenzopalazzo** [comment]
Hello @hasankaWi , it seemed strange and I tried to declare a new JLabel in the demo and I got this result, and 'equal to what you get? (ie it does not seem opaque)

![pippo](https://user-images.githubusercontent.com/17150045/44458851-caab3580-a607-11e8-9ac4-d57cdf5bd87f.png)

ps: even if the code is set to true.
if you make it opaque you can post a screen and to solve the problem you are currently trying to use the following code `nameYourVariable.setOpaque (false);`

**Comment by atarw** [comment]
Based on the [documentation](https://docs.oracle.com/javase/tutorial/uiswing/components/label.html), the current implementation's behaviour should be correct, i.e. `isOpaque()` should dictate whether or not the label's background is displayed (`true` means it should be printed, and `false` means that it shouldn't).
