### ISSUE TITLE
jbutton transparent icon issue

### ISSUE THREAD

**Issue by dis0hope** [atarw/material-ui-swing#43]
this is brilliant and it helped me a lot. but one issue when I added this to my project is that the icons that use to be transparent png files now are not transparent.

at default swing, I just had opaque set to false and contentAreaFilled set to false so the background is transparent, somehow the jar file disabled this
is it possible to release a patch for that?

i fixed most of them by changing the background colour to the same colour as my background, but some buttons where i implemented a drop shadow in the background image is still giving me problems

![not transparent](https://user-images.githubusercontent.com/42769475/44717225-ce820080-aabc-11e8-83d6-63c0b828915f.PNG) after including the jar
![transparent](https://user-images.githubusercontent.com/42769475/44717226-ce820080-aabc-11e8-8753-76292b72e1d1.PNG) at default swing
![need transparent bg](https://user-images.githubusercontent.com/42769475/44717228-cf1a9700-aabc-11e8-8af2-efc9d37a05b9.PNG) the drop shadow problem i was talking about. all these are jbuttons

**Comment by dis0hope** [comment]
another rookie question: how do you utilise the fonts included or is it used by the components by default?

**Comment by vincenzopalazzo** [comment]
Hello @dis0hope ,
If the font means the font, it is used automatically, in this version of the jar the known font is used.
For the main question I can not help you because I find myself temporarily on vacation, but surely @atarw  will solve soon

**Comment by dis0hope** [comment]
@vincenzopalazzo thanks for responding, i guess i'll wait for @atarw then😁😁

**Comment by atarw** [comment]
Fixed!
