### ISSUE TITLE
Suggestion: OSGi bundles

### ISSUE THREAD

**Issue by hamid-nazari** [atarw/material-ui-swing#45]
Since OSGi is getting more usecases around (me too!) I think it would be a proper suggestion to modify your project to produce release OSGi bundles that can easily be consumed. For instance, you may use maven's BND plugin to do the job.

**Comment by atarw** [comment]
Oops I'm sorry it hasn't been done yet, life's been getting in the way :(
The next week will be fairly busy for me so I'll try to do it by Friday, sorry for the delay

**Comment by atarw** [comment]
Oops sorry for the delay: I've added support for this (I've never used OSGi before so please tell me if I did anything wrong!)

**Comment by hamid-nazari** [comment]
Thanks, I'll check it out and will come back to you later.
