### ISSUE TITLE
Not an issue. How can I change the color of the unselected TextField to #232323?

### ISSUE THREAD

**Issue by khadapps** [atarw/material-ui-swing#46]
Sorry about that awful question, but I've tried to change on the project and build using netbeans but it gives me an error when I put the jar on my project. 

I can't find a way to do this.

**Comment by khadapps** [comment]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at mdlaf.MaterialLookAndFeel.initComponentDefaults(MaterialLookAndFeel.java:148)
	at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
	at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at MainClass.MainClass.main(MainClass.java:29)
Caused by: java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1348)
	at mdlaf.utils.MaterialImages.loadImg(MaterialImages.java:36)
	at mdlaf.utils.MaterialImages.<clinit>(MaterialImages.java:30)
	... 5 more
Java Result: 1

**Comment by vincenzopalazzo** [comment]
Hello @khadapps ,
I was thinking about how to make personalization easier, while I give you a hand in personalization, try the following piece of code after setting the look and feel.

`UIManager.put("TextField.inactiveBackground", new Color(35, 35, 35);`

I hope to be proved helpful

**Comment by khadapps** [comment]
Many thanks Vincenzo! 
But I can't make it work... 
I've tried to change "inactiveBackground" to "unfocusedBackground" but neither of them works.

**Comment by vincenzopalazzo** [comment]
@khadapps Can you post the code ?? and above all the complete exception?

**Comment by atarw** [comment]
Wait I'm a bit confused. Is the issue that Netbeans doesn't load the jar or does it have to do with the text field?

**Comment by vincenzopalazzo** [comment]
@atarw The problem is not netbinse 'cause I test the look and feel I always do it with him, rather I think his jar is corrupt.

Yesterday I was fixing a few things on my fork and I got a similar error, very similar so I think the JtextField is ok

ps: Excuse the intrusion

**Comment by khadapps** [comment]
Hello, my problem is just that I can't change the color of the unfocused background of the JTextField. 
So far I've tried things like the code `UIManager.put("TextField.inactiveBackground", new Color(35, 35, 35);` code but it didn't works.

**Comment by atarw** [comment]
Fixed!

To change the active color of a JTextfield, change `JTextfield.selectionColor`, or for the unfocused background, changing `UIManager.put("TextField.inactiveBackground", ...)` should work.

You can also change `JTextField.selectionTextColor` and `UIManager.put("TextField.inactiveForeground", ...)` for more customization
