### ISSUE TITLE
Table with Date as field is not using materialdesign cell renderer

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#58]
Hi,
I got an issue where I got a table with a tablemodel which has a tableformat that includes a Date object.
Somehow the cellrenderer doesn't use the MaterialTableCellRenderer but the DefaultTableRenderer. I think this is not supposed to happen, since I painted my Table in blue and now all Columns are blue when selected, but the cell with the Date object ist still grey.
Thanks :)
![errorwithdateintable](https://user-images.githubusercontent.com/4528294/53158384-b7cbea80-35c3-11e9-9fe6-62ba1fd71715.JPG)

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r , 

How change color a cell? you can post the code?

**Comment by Reap00r** [comment]
Sure, I can't post you a whole project, but I used to override the defaults by adding a new java class which extends the MaterialLookAndFeel. In the initComponentDefaults I set the back and foreground differently to the normal values
protected void initComponentDefaults(UIDefaults table) {
        super.initComponentDefaults(table);
        table.put("Button.background", MaterialColors.LIGHT_BLUE_400);
        table.put("Button.foreground", Color.WHITE);

and of course I had to set UIManager.setLookAndFeel(new MyNewClass()); instead of MaterialLookAndFeel.

Hope that helps :)

The reason I was doing this is to manipulate some defaults set by the Project.
Also we have a combobox with like 1-2k entries. With that, the loading time of the project was huge.. like minutes or so. So I had to change the Font that was used and it worked like a charm.

**Comment by atarw** [comment]
I'll try to take a look at this later, unfortunately I have exams going on and I won't be able to fix this until next week :/

Apologies for any inconvenience

**Comment by Reap00r** [comment]
No worries, your exams are more important ;)
I just wanted to let you know that the same problem occurs for numbers like integer values as well for me.

**Comment by vincenzopalazzo** [comment]
@Reap00r Hello, I try override method in the MaterialTableCellRenderer but I could not reproduce your problem could you kindly try this version? and let me know?

[Version beta try fix issue #58](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/0.9.7)

**Comment by Reap00r** [comment]
@vincenzopalazzo 
This fixes my problem, thanks for the update!

**Comment by vincenzopalazzo** [comment]
@Reap00r Thanks for you, I create a pull request in the new day, hoping to solve the Hover effect in the same pull request
