### ISSUE TITLE
jtable problem

### ISSUE THREAD

**Issue by vincenzopalazzo** [atarw/material-ui-swing#6]
Hello when I go to apply the theme with the following code:
`static{
	BasicLookAndFeel matirial = new MaterialLookAndFeel();
	try {
	    UIManager.setLookAndFeel(matirial);
	} catch (Exception ex) {
	    LOGGER.error("Look end feel " + matirial.toString() + " non supportato");
	    UIManager.getLookAndFeelDefaults();
	}
    }`

 the theme does not apply to jtable and I get a similar result ...
![screenshot from 2018-05-19 14-01-29](https://user-images.githubusercontent.com/17150045/40268467-e15c1220-5b6d-11e8-868c-529a97a48eac.png)

However nice initiative :)

**Comment by atarw** [comment]
Yeah, the library doesn't support JTables yet but I'll try to code something up in the next day or two for you

**Comment by atarw** [comment]
Sorry for the delay, was busy with work. I've added JTable support, complete with material design cell editing
