### ISSUE TITLE
MouseOver effect on components

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#60]
This is rather a question than an issue. I am working on a big projects with a couple of hundret buttons, a lot of menus and so on. We used a very old L&F until I found yours. Now what I am missing is like a default mouse over effect on elements. Like when you hover over a menu, it just stays white, or over a button, a tabbedPane or whatever.
Don't get me wrong, I saw that it is possible to set MaterialUIMovement and use it on everything, but that simply doesn't work for me. We use different 3rd party libraries or other stuff where I can't set the MaterialUIMovement for this and that component.
So do you think that adding a default mouse over effect would be possible?
Thanks!

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r ,

Yours refer to the added a MaterialUIMoviment into MaterialButtonUI, right?

**Comment by vincenzopalazzo** [comment]
@Reap00r 

Look at this example and ignore color :P
![screenshot from 2019-02-22 17-19-38](https://user-images.githubusercontent.com/17150045/53255617-4a54b280-36c6-11e9-91ff-33ba1a28eac3.png)
![screenshot from 2019-02-22 17-19-49](https://user-images.githubusercontent.com/17150045/53255630-4d4fa300-36c6-11e9-97db-8b717c88db08.png)

I undestend your questions?

ps: You did not explain yourself wrong, it's me that I'm learning English :)

**Comment by Reap00r** [comment]
@vincenzopalazzo 
I refer to any UIMovement. Not a specific one like in your example the button.
When I hover over a JMenu, or Elements in a JTabbedPane I want the element to somehow "pop up" or be circled with a color or so. Just so you know that it is an element which can be selected. Otherwise the people might think this is just plain text.
In this picture you see that when I CLICK the JMenu, the background is grey. Now when I hover over the menuitems while the JMenu is clicked, it also changes the color to grey. BUT when I HOVER over a JMenu it won't change the background.
![mouseoverworks](https://user-images.githubusercontent.com/4528294/53320343-b3f6db80-38d5-11e9-9827-ee310cb77084.png)

The same is for the items from a tabbed pane.

Hopefully this could help you to understand what I ment :)

**Comment by Reap00r** [comment]
I had a closer look at this link which shows a hover effect for buttons:
https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/0.9.7
Should this already work in my program when I download the attached version?
I tried it and it somehow didn't do anything to my button. I removed the part for the UI Movement in my code and added table.put("Button.mouseHoverColor", MaterialColors.GRAY_500); table.put("Button.mouseHoverEnable", true); but now it doesn't do anything while hovering.

I like the preview you did though! It really looks like what I need and if you could implement it for other components, this would really be great!!

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r, 

> Should this already work in my program when I download the attached version?

Yes, but not work, right?? sorry but here is a partial fix, to @atarw [(look this)](https://github.com/atarw/material-ui-swing/pull/61) did not like my solution and in fact these days I thought about it and it's not fantastic so tonight if I'm at a good point I want to start working on a new implementation

> I like the preview you did though! It really looks like what I need and if you could implement it for other components, this would really be great!!

Of course, yes, I have not done it yet because I wanted to find a solution millet and I wanted to understand if the effect that you have on the demo was the desired effect.

**Questions for you**
If I can ask you a question, in my relase I changed something also in terms of fort, ie I use a certain type of font based on the OS used, I could have feedback on the fonts if any?

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo ,
no problem, I'm sure you will come up with a great idea how to set this up :)

Regarding your question:
I really like the changes you did to the font. We are only using Windows, so I can only speak for that OS, but I really like it.
The changes changed the height of text and so on, and I am currently trying to resize our dialogs so the text fit in perfectly ;) Now after your changes, they might not fit in anymore.
Don't worry, I just started changing them, but if you could tell me if this is the last change regarding the font that would be great. Because if there are changes planned and I start changing the dialogs and they don't look the same in a month or so, that would be really bad ;)

**Comment by vincenzopalazzo** [comment]
@Reap00r I tried a new method for support font, indeed in platform windows the look and fell used a Windows font.

Surely I want resolve this problem, and that was a first test but I do not know what he thinks of atarw  for this ide.

You can find my planning here, I hope that when atarw he will have some time to take a look at my ideas too.

Ps: If @atarw I agree I create a pull request for font support in the official repo

**Comment by vincenzopalazzo** [comment]
@Reap00r I'm working on the full version of the pull request, but now I stop because I'm tired and I want to avoid lowering the quality of my work, so I released a version that should fix the bug of the hover mouse effect and added almost all the cursor on the components

If you try it, will you let me have news? I leave you the link [here](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/0.9.8)

ps: @atarw  I would also like to know what you think of my potential solution to the problem of the font so as to add that in the pull request if you like :)

**Comment by atarw** [comment]
Sorry I'm a bit behind - what was the font problem solution and where can I find it? I'd love to take a look at it

**Comment by vincenzopalazzo** [comment]
Hi @atarw,

Sorry, [this](https://github.com/vincenzopalazzo/material-ui-swing/blob/masternow/src/mdlaf/utils/MaterialFontFactory.java) is my solution, I used a Pattern Factory and the Singleton for reducing created All font when not necessary and using a file property for load the font according the OS.

And this are another skills I would apport, [Like it?](https://github.com/vincenzopalazzo/material-ui-swing/projects/1).

ps:Sorry for my English :/

**Comment by Reap00r** [comment]
Hey @vincenzopalazzo,
I took a look at your example and saw that when you hover over any element (e.g.) button where the background color should change, this ONLY happens when you move the mouse away from the current element and hover over it again. I think that is a bug and should work directly when you hover over an element.
But I like the rest though ;)

**Comment by vincenzopalazzo** [comment]
Hey @Reap00r, Thanks for trying my new test update and sorry if he contains an error but I do not understand the problem, your result is different to this gif [Click me](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V0.9.8)?

Sorry for my difficulties with English

**Comment by atarw** [comment]
Just pulled in the change - I cracked my laptop screen and won't be able to fix it until next week. I accepted @vincenzopalazzo's pull request though so hopefully that fixes the issue

**Comment by vincenzopalazzo** [comment]
@Reap00r We wait for your feedback :)

**Comment by Reap00r** [comment]
@vincenzopalazzo Sorry for being late. I had a look at your example again and this time it worked like it should.

**Comment by vincenzopalazzo** [comment]
@Reap00r 

> @vincenzopalazzo Sorry for being late. I had a look at your example again and this time it worked like it should.

I love this answer :) then is OK, see you later in nex moment :) thanks for having permitted added new skills at the look and feel with you help and you issue :)

**Comment by Reap00r** [comment]
@vincenzopalazzo I had a third look at your example and wanted to ask if you added a functionality so the effect for the mouse-over (like you did for JButton) is also added to Menu, Menuitems, Elements from a TabbedPane and so on. 
Maybe I didn't see it, so thanks for helping me :)

**Comment by vincenzopalazzo** [comment]
@Reap00r I working on, in this week hope finish work.

I wanted to be sure that code work :) the fix will arrive coming soon

**Comment by Reap00r** [comment]
@vincenzopalazzo Great! Thanks for doing this :)

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,

I added the effect mouse hover on the JMenu and row on Jtable, can you test my work, please? :)
[new skill](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V0.9.8)

> TabbedPane and so on

Can you give me an example?

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo 
your changes in regards to the hover effect work for all buttons now. But the changes for the different mouse curser doesnt work for all of them. Here it works:
![gifworks](https://user-images.githubusercontent.com/4528294/53940002-d4cce700-40b4-11e9-96f0-f16d527bce63.gif)
Here it doesn't:
![gifnotworking](https://user-images.githubusercontent.com/4528294/53940061-f9c15a00-40b4-11e9-90cb-e517e33aadc0.gif)
In the example where it is not working you can see that I hover over a tabbedPane element ("Dokumente") and in my opinion it should change the Background of the selected element to a different color or change the cursor. Like the hover effect has light grey and the click effect changes it to a darker grey. This is just ment as an example.

I like the changes you did to the JMenu!

And now one thing that I don't like about your change is the new effect for the JTable.
When I hover over an element in the table, it automatically selects it. I thought you wanted to change only the background when hovering, not select the element. In my case, when I select an item, it loads pretty many thing and displays them. Now after your update, when I just hover over the elements, all of them are selected and all those things are loaded and displayed shortly. This takes a pretty long time and also looks pretty strange, since things get updated in the view even though nobody clicked on them.
Additionally: When I hover over the elements, it changes the background color on every element. Now when I select it, the selected element keeps the background color. When I hover over other elements in the table, they don't change the background color anymore. When I now click on another element in the table, the background color from the recently selected item is removed, but the new element isn't selected! Now I have to click on it again to select it.
![giftable](https://user-images.githubusercontent.com/4528294/53940981-49a12080-40b7-11e9-8da8-8f14f67d7383.gif)
I hope this gif makes things clearer :)
I would suggest that there is always a color when hovering and only when i click on the element, it changes to a different color, but when I continue hovering, the hovering color is still displayed for the other elements.

I hope I could make clear to you what I like / dislike. If not, just tell me and I will try to find a way to explain it :)

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r, 
Thanks for your help, I'm trying to add a hover mouse effect to the table bread and I had not thought that if I declared the selected line I could create problems.

The thing of the buttons is really bizarre, I'll try to take a look at what happens

for now, thanks, I added all your problems in my schedule.

do you think that if the mouse hover on the table works well, is it a cool thing?

**Comment by Reap00r** [comment]
Hello @vincenzopalazzo 
thank you for spending the time on fixing this :)

I don't know if I am the right person to ask in regards to visual designs ;) I think it could look cool. But the hovering effect has to be different than the actual selected color. If you could do that, I think that would be great. Also making it possible to switch it on and off would make it more versatile.

**Comment by vincenzopalazzo** [comment]
@Reap00r, Thanks for your idea, I will work on :)

do not regret me, the merit is @atarw  for creating a look and feel so cool.

See you at the next fix :-)

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,

This [version](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V0.9.8) contains a mouse hover for JMenu and JTabbledPane, I removed mouse hover for rows JTable because the code I'm not like, I will try it in next time.

I continue with the pull request but you let me know if there are any bugs

**Comment by Reap00r** [comment]
Hello @vincenzopalazzo,

I like the changes for the JMenu and JTabbedPane.
I also checked the changes for the JXTabbedPane and I like them as well :)

> Here it doesn't:
In the example where it is not working you can see that I hover over a tabbedPane element ("Dokumente") and in my opinion it should change the Background of the selected element to a different color or change the cursor. Like the hover effect has light grey and the click effect changes it to a darker grey. This is just ment as an example.

I dont't think that is related to your code. I think my code is doing something wrong, so if you are still checking what the problem is, I think you can stop.

A couple of things that I noticed:
The combobox react a little bit strange
![gifcombobox](https://user-images.githubusercontent.com/4528294/54030397-c3b2d180-41ab-11e9-9f19-5c0cd6b8bd86.gif)
I think it is good that it changes the color when you hover over it. But I think it should change it back to the default color (white) when you leave the element. Additionally, there are strange black lines / bars when you hover over it. I have really no clue how this can happen, but you can see it pretty well in that gif.

Regarding Textfields: Did you change anything regarding the fonts? I just noticed that the cursor in the textfield is too close to the line that indicates where the textfield is, see the gif. Shouldn't there be more space between the cursor and the line?
![giftextfield](https://user-images.githubusercontent.com/4528294/54030661-9f0b2980-41ac-11e9-9068-99693b1b763a.gif)

Thanks for your help!

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,

Good, thans so much
> I like the changes for the JMenu and JTabbedPane.
I also checked the changes for the JXTabbedPane and I like them as well :)

Do you refer at this arrows?
![selection_018](https://user-images.githubusercontent.com/17150045/54035113-dd0e4a80-41b8-11e9-99da-995c8e40afff.png)
![selection_019](https://user-images.githubusercontent.com/17150045/54035116-e0a1d180-41b8-11e9-8e73-18a823e02e6e.png)
 
The combo box is formed at the button if you change color in the all "mouse hover color effect" for button in the UIDefault, change also the combo box button, I will try resolve this difference

> A couple of things that I noticed: The combobox react a little bit strange

This fix is in programe the my scheduler project

> Additionally, there are strange black lines / bars when you hover over it. I have really no clue how this can happen, but you can see it pretty well in that gif.

Damn, this bug is caused of me, when I solved the issue #37, I will try resolve this problem

> Regarding Textfields: Did you change anything regarding the fonts? I just noticed that the cursor in the textfield is too close to the line that indicates where the textfield is, see the gif. Shouldn't there be more space between the cursor and the line?

**Comment by Reap00r** [comment]
@vincenzopalazzo 

> Do you refer at this arrows?
selection_018
selection_019
Yes, exactly.

> The combo box is formed at the button if you change color in the all "mouse hover color effect" for button in the UIDefault, change also the combo box button, I will try resolve this difference

but you resolve this problem temporarily with this code.
comboBox.addMouseListener(MaterialUIMovement.get(..))
Thanks for the hint ;)

**Comment by vincenzopalazzo** [comment]
@Reap00r, you have the same problem with the arrows?

**Comment by Reap00r** [comment]
@vincenzopalazzo  no, I was just talking about switching the icons for expanding and collapsing the tree. Which problems are you talking about?

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,

> no, I was just talking about switching the icons for expanding and collapsing the tree. 
Do you have something to recommend?

> Which problems are you talking about?
I hope none :), it was my incomprehension sorry.

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo ,
I don't want to change the icons you are using, I just want to switch the icons. What I mean is, that I would show the ">" icon when it is opened (expanded)  and the down arrow when it is closed (collapsed). Currently it is the other way round.

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,

Oh ok, I will make the changes in the nex pull request :), should arrive before the my travel.

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
I just created 3 issues, 1 for the textfield, 1 for the combobox and 1 for the jxtabbedpane. Hope that was what you wanted me to do :)

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,
Thanks for your help :). it was what I wanted

Yesterday I started work in the bit update the look and feel, look [this](https://github.com/vincenzopalazzo/material-ui-swing/commit/2e2d567ecb4cb55a761bbec869097883e627097f)
