### ISSUE TITLE
Gap between text and textfield is too short

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#65]
I just noticed that the cursor in the textfield is too close to the line that indicates where the textfield is, see the gif. Shouldn't there be more space between the cursor and the line?
![GIFTextfield](https://user-images.githubusercontent.com/4528294/54111209-a2d4c100-43e3-11e9-8d4d-f6df613e98c4.gif)

**Comment by atarw** [comment]
Closing as it seems to be fixed
