### ISSUE TITLE
Switch Icons for JXTabbedPane

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#66]
Hello @vincenzopalazzo 
I would show the ">" icon when it is opened (expanded) and the down arrow when it is closed (collapsed). Currently it is the other way round.

**Comment by vincenzopalazzo** [comment]
Hello @Reap00r,  I'm preparing a pull request, the bugs were resolved.
The pull request it will be published on Wednesday evening

Stay tuned :P

**Comment by Reap00r** [comment]
Hello @vincenzopalazzo, thanks for the update. I will be out of town from today until sunday. So unfortunately I can't test your changes right away when they are released.

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,
No problem, If are present the new bugs, we will fix it :)

**Comment by atarw** [comment]
Finally got my laptop screen fixed, thank you for fixing this issue @vincenzopalazzo!! I'll close this issue if everythings working

**Comment by vincenzopalazzo** [comment]
@atarw I'm happy for your screen.
I saw that you closed all the problems of my fixes, and I assume that everything worked, right?

I wanted to ask you if you'd like me to help you develop the look and feel and maybe work together on developing new skills :)
