### ISSUE TITLE
Drop Shadow Isn't under Pane

### ISSUE THREAD

**Issue by KvnXu** [atarw/material-ui-swing#69]
I am using this code:
`contentPane.setBorder(new DropShadowBorder(new Color(0, 0, 0), 1, 5, .3f, 12, false, false, true, false));`
Which results in this issue:
![a34v](https://user-images.githubusercontent.com/35074883/54503877-3a17a800-48ff-11e9-9174-60c2b7e23086.png)
Note that the shadow sits on the pane and not under it like a border should.
I get the same issue when using:
`contentPane.setBorder(new DropShadowBorder());`
![z86j](https://user-images.githubusercontent.com/35074883/54503956-7e0aad00-48ff-11e9-9e60-fd88ac9bd5ea.png)

**Comment by vincenzopalazzo** [comment]
Hello @KvnXu,

I am away from home during this time and I cannot see your problem before Wednesday evening.
But I have a question for you, what is the effect you want to get by adding that code ??

**Comment by KvnXu** [comment]
The shadow is on the pane instead of around it like a border should

**Comment by atarw** [comment]
There isn't much you can do about that unfortunately. As far as I can tell swing doesn't really support translucent borders as it reserves a "box" for that component including the border so it's impossible for the shadow to overlap with another component in the way you want.

I suggest changing the background colour of the drop shadow to match the red but other than that there isn't much else you can do :/

**Comment by vincenzopalazzo** [comment]
@KvnXu [This](https://stackoverflow.com/questions/19105242/undecorated-jframe-shadow?rq=1) could resolve your problem
