### ISSUE TITLE
Error in MaterialUIMovement.add (button, new Color (34, 167, 240));

### ISSUE THREAD

**Issue by Ramneek-kalra** [atarw/material-ui-swing#7]
Have a look over this statement in Netbeans IDE, that's not working in it. And, secondly, I am unable to get the material look and feel after running, Please do see in the issue.

Ramneek

**Comment by atarw** [comment]
Hi, just to make sure it's not an import issue, can you make sure you properly included the library jar file into your project? I don't use netbeans but you can probably look up how to do so online.

If the issue still exists, can I get a screenshot to help find the problem? Specifically, one of the error you get with that particular statement and your GUI window after applying the look and feel, thanks!

**Comment by Ramneek-kalra** [comment]
Okay not a problem, if any problem persists, I will then share you the screen shot. 
Thanks for sharing the repository!

**Comment by atarw** [comment]
Going to close this, if you run into any more issues, feel free to let me know!
