### ISSUE TITLE
Buttons with opaque false are rendered pixelated at the sides

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#71]
Hi,
since your latest updates the buttons look quite strange in my program.
I set button.opaque(false) and now it looks bad for either the JTaskPane Header and the normal JButtons as well.
This is how it looks for me right now:
![taskPaneNotWorking](https://user-images.githubusercontent.com/4528294/54813295-83645080-4c8d-11e9-8eb1-02d6cdc972bc.JPG)

This is how it used to look:
![taskPaneWorking](https://user-images.githubusercontent.com/4528294/54813278-7e9f9c80-4c8d-11e9-9159-9c7004e12868.JPG)

I am not quite sure, but maybe this is related to your fixes here:
https://github.com/atarw/material-ui-swing/issues/64

The arrows where increased in size as well and I am not quite sure if I like them, but that might be another issue.

**Comment by vincenzopalazzo** [comment]
@Reap00r I added the new icons for a test, for the moment you can change the icons with the UIDefault

```
table.put("TaskPane.yesCollassed", new ImageIcon(MaterialImageFactory.getIstance().getImage(MaterialImageFactory.YES_COLLASSED)));
table.put("TaskPane.noCollassed",   new ImageIcon(MaterialImageFactory.getIstance().getImage(MaterialImageFactory.NO_COLLASSED)));
```

**Comment by Reap00r** [comment]
In the latest version there is no more class MaterialImageFactory. 
I used to do that to turn around the pictures but now I can't find this class anymore

**Comment by vincenzopalazzo** [comment]
@Reap00r in my version is introducing a MaterialImageFactory but I using a Pattern Factory for not load all image in the bootstrap app.
In the @atarw not is present this pattern but is present MaterialImage.YES_COLLASSED

But the old icons aren't include, sorry I adding in this day your favorite icon :)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,

This bug is not present in Linux and Windows, do you still see this bug?Otherwise you could close the issue, all these issues bring anxiety :)

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,

I am currently working with the latest version of this project. I used maven to build the jar (first cleaning, then deploying) and in result, I got a material-ui.swing-0.9.3.3.jar in the target folder of the project.
I then switched the version you gave me since your last fix with this version and now I see the following problems:
Opaque buttons that are set to false are rendered pixelated
Combobox still looks strange when hovering over it
There is no hovering effect on the JMenu.

For example, when I start his swing demo and set button opaque to false I see the same results.

If I am doing something wrong in terms of building the right version or so, please tell me what I should do instead :)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,

The version 9.3.3 is the last version released atarw, I create the jar now and I see the bug
- There is no hovering effect on the JMenu.
- Opaque buttons that are set to false are rendered pixelated because the border is not valid
- Combobox still looks strange when hovering over it
- JSpinnet mouse hover problem *(On windows, this problem is very accentuated but it is clear that there is a bug)*

These should be all problems, right? so let's put some order in order so even when he enters atarw he won't find a mess.

You can open the issues for every single associated issue and start working this evening so you can get a stable version by the beginning of next week.

Sorry for the inconvenience

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
I just created an issue for all of them. I will close this issue now.
Don't worry, I believe in you :) You already did a bunch of good things, and in terms of coding there is always a possiblity of something bad happening with a strange side effect ;)
Thanks for taking your time and fixing those issues!
