### ISSUE TITLE
Opaque buttons that are set to false are rendered pixelated because the border is not valid

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#73]
![pixeledBorder](https://user-images.githubusercontent.com/4528294/54983283-c2a3e180-4fac-11e9-828b-246b30902230.JPG)
In earlier version, the buttons looked nice

This is related to: https://github.com/atarw/material-ui-swing/issues/71

**Comment by vincenzopalazzo** [comment]
Some problems were doubt to me, the fault of keeping the two versions aligned. sorry

Now I hope this problem is solved

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
it seems to me that no matter if I set buttons to opaque true or false, they look exactly the same. The borders of the button with opaque false should be somewhat round.
This is how they look no matter what I set opaque to:
![noRoundBorder](https://user-images.githubusercontent.com/4528294/55225446-eb2d1500-5212-11e9-9a25-2ca206891955.JPG)

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
it seems like the buttons look the same now, with or without opaque false. They don't look round at the edges as they are supposed to.
This is how they look no matter what I set them to:
![noRoundBorder](https://user-images.githubusercontent.com/4528294/55225546-2c252980-5213-11e9-9fbd-77c4e1557dcd.JPG)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,
can you give me an example on how you want me to paint the button when it is setOpache to true and when it is false? I tell you how I imagine it, when the button is opaque then it has the same color as the analogue panel when it is not opaque, it takes the color of the button set in the UIDefault, do you want this effect? sorry but I never had the need to use this swing feature which for some other components is useless, I leave you this reference from where I read something https://stackoverflow.com/q/2451990/10854225

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
sure, here is an example how it used to look in an earlier version of this project:
https://user-images.githubusercontent.com/4528294/54813278-7e9f9c80-4c8d-11e9-9159-9c7004e12868.JPG
and if it is set to false, it should look like that again.

When it is set to true, it should look like that:
![noRoundBorder](https://user-images.githubusercontent.com/4528294/55239104-44f30680-5236-11e9-8ef1-28adeb596a90.JPG)

Maybe you could checkout an older version of the repository and compare what change in between the version which changed the button to look pixelated.

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,

So the effect that should appear is:

**When button.setOpache (true)**:
 - border rectangular

**When button.setOpache (false)**:
- Border not rectangular rounded

Did I get it right?

**Comment by vincenzopalazzo** [comment]
@Reap00r After a long time I understand your problem, excuse my poor English skills but I'm going through a workload period.

I hope this bug no longer exists

**Comment by Reap00r** [comment]
@vincenzopalazzo no worries, you are trying your best and we are able to communicate with each other :) 
And now you understood what I wanted 👍

**Comment by vincenzopalazzo** [comment]
@Reap00r Thanks, the fix are inside [this](https://github.com/atarw/material-ui-swing/pull/78) pull request.

I hope of the fixing the problem with this solution

**Comment by Reap00r** [comment]
@vincenzopalazzo thanks for the fix, now it looks as good as it used to :)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r, 
I noticed the presence of this error only after several days because it is a problem at one point in the code that we never touched and something like that didn't seem possible to me.
But every time even the Graphics was used and not Graphics2d everything came out pixeled.

I say this also for informational purposes if I use graphics with the look and feel you might get pixeled drawings
