### ISSUE TITLE
Combobox looks strange when hovering over it on Windows

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#74]
The hovering effect on windows draws strange things onto JCombobox
![GIFComboboxWrong](https://user-images.githubusercontent.com/4528294/54983527-59709e00-4fad-11e9-84bb-ff07330b0d30.gif)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,

The problem has the border arrow button,

I hope this issue is fixed

**Comment by Reap00r** [comment]
Closing this because it's working. Great work
