### ISSUE TITLE
JSpinner mouse hover problem

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#75]
When you hover over the spinner elements, they either draw the last hovered color see first GIF or draw strange things onto the spinner

![GIFHover1](https://user-images.githubusercontent.com/4528294/54983624-8329c500-4fad-11e9-99b0-659bb38b2837.gif)

![GIFSpinner](https://user-images.githubusercontent.com/4528294/54983875-f4697800-4fad-11e9-800e-f29b3b77b610.gif)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,

The problem has equal to combo box,

I hope this issue is fixed

**Comment by atarw** [comment]
Merged, going to leave this open in case there are still any issues

**Comment by Reap00r** [comment]
Closing this because it's working. Great work
