### ISSUE TITLE
JTree support

### ISSUE THREAD

**Issue by RubrumExPlaneta** [atarw/material-ui-swing#8]
It would be really nice if `JTree`s were supported.
It seems that currently, they are not supported.

**Comment by atarw** [comment]
I'll work on it over the weekend :)

**Comment by RubrumExPlaneta** [comment]
@atarw Thank you for the quick reply. :)
Not only is your work really aesthetically appealing, you seem to be really actively maintaining it; you really deserve more credit and I am surprised this repository is not much more well known that it is. Keep up the good work!

**Comment by atarw** [comment]
Thanks for the kind words ❤️
The latest release should support JTables now

**Comment by RubrumExPlaneta** [comment]
Thank you, I did not get to test it yet but that was really quick!
