### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by kvnxu** [atarw/material-ui-swing#83]
I tried out the new release, and I couldn't get it to work. I got a NoClassDefFoundError when setting the LookAndFeel. However, the release before this one works fine.

**Comment by vincenzopalazzo** [comment]
Hi @kvnxu,p what is you jar?!

Tha official ja last version not exist but you have two chance
- clone the repo and run comand with maven
- attend @atarw of the load new version but I remember corret he is a little engaged.

In last alternative the last update is do of me and you find the last jar update here(https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V1.0.Beta1.1) this jar contains the new style of the JDialog into versione the testing

**Comment by kvnxu** [comment]
I downloaded the jar from https://github.com/atarw/material-ui-swing/releases/tag/v0.9.4.0, this was the one that didn't work properly. Your version works fine, however. I'll likely be using it over the old one from this repo. Thanks.

**Comment by vincenzopalazzo** [comment]
I'm happy if you using a material-ui-swing and my solution work, The jar into 0.9.4.0 is not official jar.
We work on this project for creating a look and feel cool and my repo and the repo of the @atarw are equal.

I will think about how to provide a more effective beta release channel, sorry for the inconvenience and sorry my terrible English

**Comment by atarw** [comment]
Sorry about that I've updated the latest release to be consistent with the master branch.

Yeah I'm planning on keeping this repo as the "stable" version while @vincenzopalazzo's repository has more experimental/additional features
