### ISSUE TITLE
ActionListener not firing 

### ISSUE THREAD

**Issue by itsTyrion** [atarw/material-ui-swing#84]
After setting the material l&f, a JTextField's action listener doesn't seem to fire when pressing return for me. commenting the setLookAndFeel part out resolves the issue.

snippet https://pastebin.com/g2q4gMN5 (I removed anything not explicitly needed for this gh issue)

**Comment by vincenzopalazzo** [comment]
HI @itsTyrion,

We work on the version 1.0 in this and in this [branch](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V1.0.Beta1.2), you tried the last version, can you try your code in with the last update, please?

**Comment by itsTyrion** [comment]
Same thing. :/  tried the compiled beta 1.0 jar)
Hitting return does for some odd reason not fire an ActionEvent, the JButton is working, though.
I wonder how that is even possible o.O

**Comment by vincenzopalazzo** [comment]
@itsTyrion Thanks so muck, we will find the problem, thanks

**Comment by vincenzopalazzo** [comment]
Hi @itsTyrion I ran your code and I work well if you submit with enter the JTextField in the console printed the _aaaaaaa_.
If you want that print _aaaaaaa_ on click you must add a MouseListener.

@atarw can you close the issue please, if you can

**Comment by itsTyrion** [comment]
What are you talking about? It does not work as it should. Please just read what i wrote... “it does not fire when I press enter” and “del doesn’t work”
Why would I need a mouse listener for that? o.O

Are you running it on windows? If so, it could be a very weird platform dependent glitch.

**Comment by vincenzopalazzo** [comment]
@itsTyrion, when I press, enter in the my Demo worked on Linux, now I will try with windows

When version Java you used?

**Comment by itsTyrion** [comment]
Sooo. I finally got the time to test it. 
At first: Please exucde my rudesness in the previous reply, I didn't have your name as the dev name in my head and thought it was just some know-it-all
2nd: It IS working with the current stable, and the current beta version. 
I had a REALLY old version of Material UI Swing stuck in IntelliJ (I started the project ages but lost time and interest) and it seems like it was overriding the new version. 
And because I added the old jar under "Project Structure -> Modules -> Dependencies", it didn't show up under "Project Structure -> Libraries", which is why I didn't see it.
Sorry for wasting your time. 
![image](https://user-images.githubusercontent.com/17730120/61945955-9a9bad80-afa1-11e9-93ff-94b18335c970.png)

Nice work, thanks for making this, keep going^^

p.s. One thing I noticed with the beta jar: 
The scrollbar in a JScrollPane set to ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS behaves like ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS. 
(I thought I might ask if this is intended before opening an issue for the beta). And the font doesn't look as smooth and clean as in 0.9 (or earlier, with Roboto) (visible on your screenshots).

**Comment by vincenzopalazzo** [comment]
Hi @itsTyrion,

I'm heppy that the your version work well.

Don't worry
>At first: Please exucde my rudesness in the previous reply, I didn't have your name as the dev name in my head and thought it was just some know-it-all

Thanks so much
>Nice work, thanks for making this, keep going^^

Sorry if do this question but can you give me an example for this problem?
>The scrollbar in a JScrollPane set to ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS behaves like ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED.

The font Roboto was been removed for resolve this [issue](https://github.com/atarw/material-ui-swing/issues/42) now the font is the noto sans and whit some SO has the problem with display, this my [pull request](https://github.com/atarw/material-ui-swing/pull/79) tried to fix the problem.
On linux, this problem is more evident.

Thanks for your support :)

**Comment by vincenzopalazzo** [comment]
@atarw can you close this issue, please? because of this [PR](https://github.com/atarw/material-ui-swing/pull/86) fix it

**Comment by vincenzopalazzo** [comment]
Hi @itsTyrion, I'm linking an issue to the purpose to set a personal Font with MaterialTheming System https://github.com/vincenzopalazzo/material-ui-swing/issues/87.

I hope it resolves your problem
