### ISSUE TITLE
Focusing on a table cell will insert the last value

### ISSUE THREAD

**Issue by MJ-DEV91** [atarw/material-ui-swing#88]
Hi. Thanks for this great LAF.
Assume that I have a table and I insert "a sample value" in a cell. When I double click on another cell (even if it's been filled already), the last value that I inserted ("a sample value") will be inserted in this cell.

**Comment by vincenzopalazzo** [comment]
Hi @MJ-DEV91 

> Hi. Thanks for this great LAF.

Thanks :)

>Assume that I have a table and I insert "a sample value" in a cell. When I double click on another cell (even if it's been filled already), the last value that I inserted ("a sample value") will be inserted in this cell.

Can you give me a minimal example of reproducible, please? 

This seems a particular mistake, if you give an example we will be able to debug and focus directly on the problem.

Thanks

**Comment by MJ-DEV91** [comment]
Just in your demo application:
https://pasteboard.co/IE3vnv5.jpg

There is a table with four cells: "a", "b", "c", "d"
I filled the "a" cell with "11111" and when I double clicked on "b" cell, it was filled automatically with "11111".

**Comment by vincenzopalazzo** [comment]
@MJ-DEV91 Thanks, give me time to verifying and reproduce it. I will return

**Comment by vincenzopalazzo** [comment]
@MJ-DEV91 I have reproduced the but, I will try to fix it in the developer for [this project](https://github.com/vincenzopalazzo/material-ui-swing/issues/84).

Thanks for your help.

**Comment by vincenzopalazzo** [comment]
The bug is fixed in this [minor version](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V1.0.6).

For the moment I don't create the pull request in the official version because I have a new feature to add at the theme.
If you want you can use version 1.0.6.

**Comment by MJ-DEV91** [comment]
Thanks a lot
