### ISSUE TITLE
MaterialButtonUI.java depends on JavaFX

### ISSUE THREAD

**Issue by markscottwright** [atarw/material-ui-swing#95]
I assume this is a bug, since this is specifically a Swing look and feel.  Deleting line 2 allows maven to build on a machine without JavaFX installed.

**Comment by vincenzopalazzo** [comment]
Hi @markscottwright thanks for this.

It's only refused.

I will remove it in the next release.

**Comment by vincenzopalazzo** [comment]
HI @markscottwright,

At the moment I released [material-ui-swing 1.1.1 pre-release 6.1](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease) in the development project and this fixed this issue.

In this github project, the release coming in the next week.

Thanks for your contributing

**Comment by vincenzopalazzo** [comment]
I'm marking this issue of how resolved and I'm closing it.
