### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by YiluoE** [atarw/material-ui-swing#96]
UI 真的很不错！但是中文乱码该如何解决呢? 谢谢

**Comment by vincenzopalazzo** [comment]
HI @YiluoE 

> UI 真的很不错！

Thanks so much for your kind words.

> 但是中文乱码该如何解决呢? 谢谢

It is a problem of the personal font "Noto Sans" used inside the library.

Inside this library, we are trining to build minimal documentation through other issues.

I added a solution to fix the Chinese language through MaterialTheming, you can read the solution [here](https://github.com/vincenzopalazzo/material-ui-swing/issues/87)

You can find other documentation inside this repository [atarw/material-ui-swing]( label:doc ) and inside this repository [vincenzopalazzo/material-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing/issues?utf8=%E2%9C%93&q=+label%3Adoc+)

**Comment by YiluoE** [comment]
非常感谢你的及时回复！

**Comment by vincenzopalazzo** [comment]
I'm marking this issue of how resolved and I'm closing it.

**Comment by YiluoE** [comment]
> 我正在标记此问题的解决方法，目前正在关闭中。

在你给的方案中 很好的解决了中文乱码的问题！

**Comment by vincenzopalazzo** [comment]
@YiluoE Thanks your contributing.
