### ISSUE TITLE
GuiBuilder ?

### ISSUE THREAD

**Issue by Fusked** [atarw/material-ui-swing#98]
Hello , did material ui swing work with any scenebuilder/guibuilder ?

**Comment by vincenzopalazzo** [comment]
Hi @Fusked,

Material-ui-swing is an l&f, don't use any personal component, an example: JMaterialButton, but customize the native JButton with a swing component called ButtonUI.

So, I think that material-ui-swing work with a GUI builder, I tried to use Matisse with Netbeans and the library worked.

**Comment by Fusked** [comment]
Okay thank u very much

**Comment by vincenzopalazzo** [comment]
I'm marking this issue of how resolved and I'm closing it.
